# Generated by Django 4.1.1 on 2022-10-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_address', models.CharField(max_length=5)),
                ('availablity', models.BooleanField(default=True)),
                ('in_process', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
