# Generated by Django 4.1.1 on 2022-10-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='in_process',
            field=models.BooleanField(default=False),
        ),
    ]
