# Generated by Django 4.1.1 on 2022-10-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_parkingspace_in_process'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspace',
            old_name='availablity',
            new_name='availability',
        ),
    ]
