# Generated by Django 4.1.1 on 2022-10-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_rename_availablity_parkingspace_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
