# Generated by Django 4.1.1 on 2022-10-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_parkingspace_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='vehicle_id',
            field=models.CharField(default='', max_length=6),
        ),
    ]
