# Generated by Django 4.1.1 on 2022-10-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_parkingspace_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='vehicle_id',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
